# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mensagem.proto
# Protobuf Python Version: 7.36.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    2,
    '',
    'mensagem.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emensagem.proto\"2\n\x0cLoginRequest\x12\x0f\n\x07usuario\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"A\n\rLoginResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x0c\n\x04\x65rro\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\":\n\x11\x43riarCanalRequest\x12\x12\n\nnome_canal\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"F\n\x12\x43riarCanalResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x0c\n\x04\x65rro\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"(\n\x13ListarCanaisRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\"9\n\x14ListarCanaisResponse\x12\x0e\n\x06\x63\x61nais\x18\x01 \x03(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mensagem_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=18
  _globals['_LOGINREQUEST']._serialized_end=68
  _globals['_LOGINRESPONSE']._serialized_start=70
  _globals['_LOGINRESPONSE']._serialized_end=135
  _globals['_CRIARCANALREQUEST']._serialized_start=137
  _globals['_CRIARCANALREQUEST']._serialized_end=195
  _globals['_CRIARCANALRESPONSE']._serialized_start=197
  _globals['_CRIARCANALRESPONSE']._serialized_end=267
  _globals['_LISTARCANAISREQUEST']._serialized_start=269
  _globals['_LISTARCANAISREQUEST']._serialized_end=309
  _globals['_LISTARCANAISRESPONSE']._serialized_start=311
  _globals['_LISTARCANAISRESPONSE']._serialized_end=368
# @@protoc_insertion_point(module_scope)
